### ISSUE TITLE
Canvasses broken steamport fix now pls

### ISSUE THREAD

**Issue by epicss13gamer** [HippieStation/HippieStation#12081]
[Round ID]: 44567

[Reproduction]: Just get a fucking canvas in anyway possible, I ordered it from cargo, ahelped it, memerino nigga tried to spawn that shit, its fucking broken

Holy shit my dumbass didnt even explain the bug, simply, canvases are just not fucking existant.

**Comment by yoyobatty** [comment]
```
//HEY YOU
//ARE YOU READING THE CODE FOR CANVASES?
//ARE YOU AWARE THEY CRASH HALF THE SERVER WHEN SOMEONE DRAWS ON THEM...
//...AND NOBODY CAN FIGURE OUT WHY?
//THEN GO ON BRAVE TRAVELER
//TRY TO FIX THEM AND REMOVE THIS CODE
/obj/item/canvas/Initialize()
	..()
	return INITIALIZE_HINT_QDEL //Delete on creation
```

**Comment by yoyobatty** [comment]
//HEY YOU
//ARE YOU READING THE CODE FOR CANVASES?
//ARE YOU AWARE THEY CRASH HALF THE SERVER WHEN SOMEONE DRAWS ON THEM...
//...AND NOBODY CAN FIGURE OUT WHY?
//THEN GO ON BRAVE TRAVELER
//TRY TO FIX THEM AND REMOVE THIS CODE
/obj/item/canvas/Initialize()
	..()
	return INITIALIZE_HINT_QDEL //Delete on creation

This is not a bug

**Comment by epicss13gamer** [comment]
F
