### ISSUE TITLE
Put devil back in rotation

### ISSUE THREAD

**Issue by epicss13gamer** [HippieStation/HippieStation#12159]
[Implementation]: # Honk.

[Why]: # Devil doesn't happen enough as it is a really interesting gamemode.

[Resources]: # devil_game_mode.dm

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by diegoxt45** [comment]
it ins't that interesting of a gamemode + it's already on dynamic and i'm fine with how frequent it happens

**Comment by AnthonyJNgo** [comment]
Devil was recently buffed so this may be an interesting suggestion actually.
@designer

**Comment by epicss13gamer** [comment]
> it ins't that interesting of a gamemode + it's already on dynamic and i'm fine with how frequent it happens

Oh, if it happens on dynamic, thats good. Im not saying it has to happen every fucking round or so. I just want it to be available as a gamemode.

**Comment by Manly-Dwarf** [comment]
no, it's horrible, and it's already in dynamic albeit very rare.
