### ISSUE TITLE
[Sugg] Forge "Rework"

### ISSUE THREAD

**Issue by TrickyDickRichard** [HippieStation/HippieStation#12262]
[Title]: Forge "Rework"

[Implementation]: Here's my idea:
The way you make tools using the forge currently makes no sense. A weapon made completely out of one metal would vibrate upon impact and your hand would get nerve damage. Real tools are made by mounting a tool head to a tool rod, so I feel the way to make a forged tool should be to make a tool head at the forge and then mount it to a tool rod. I have an idea that there would be 3 different sizes of tool rod for how big the tool is, such as a huge rod for warhammers, large rod for maces, and tiny rod for daggers.

[Why]: It would make forged tools more interesting, and the addition of different materials for tool rods could make it a bit like the Tinkers Construct mod for MC. Besides, I'm already making sprites for a tool system Viv has in mind for Dwarves.

[Resources]: My sprites for this shit:
![donut](https://user-images.githubusercontent.com/7635106/73498278-d4070880-438a-11ea-8c97-bcc5462e5903.png)

Download this file and rename it from "forgetools pic.png" to "forgetools pic.dmi" to see it in the DM.

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by yoyobatty** [comment]
That is actually an interesting idea, I'm all for it.

**Comment by mkikt4743** [comment]
seems cool and realistic, but also doesn't, make game less fun, go for it

**Comment by TrickyDickRichard** [comment]
I'm just a spriter, would need someone else to code it

**Comment by karmaisblackandbluepilled** [comment]
i was gonna mention that it sounds like tinker's but then you said it in the desc LOL
+1 good idea I'm gonna fucking coom.

**Comment by TrickyDickRichard** [comment]
we could go full TC on this but without a coder we ain't gonna get shit done

**Comment by GuyonBroadway** [comment]
Add throwing knives and I'm sold.

**Comment by TrickyDickRichard** [comment]
still got the sprites for those
![flying knife but that shit greyscale pic](https://user-images.githubusercontent.com/7635106/68533657-6bfbd580-02f9-11ea-80e0-d66fc10d70f9.png)

**Comment by thichbriars** [comment]
you still want to work on this? ive been intrested in working on the forge. Cant sprite or anything though.

**Comment by TrickyDickRichard** [comment]
has anyone really worked on this past me doing the sprites and making the idea?

**Comment by thichbriars** [comment]
i dunno. im completely new to byond coding, but if you still wanna work on it id be down

**Comment by TrickyDickRichard** [comment]
shoot me with a sprite you need and i'll make it

**Comment by FantasticFwoosh** [comment]
These look clean, i approve.

Could we make weapons with considerable strength accept a leather grip (1-2 sheets) in the construction recipie? Mainly to stop rushing with minimal resources and add artistic finesse to the exposed pole.

Any chance of pickaxes and shovel heads being equipped onto any mini or medium tool-stick for their respective portable subtypes?

**Comment by TrickyDickRichard** [comment]
> Could we make weapons with considerable strength accept a leather grip (1-2 sheets) in the construction recipie? Mainly to stop rushing with minimal resources and add artistic finesse to the exposed pole.
that sounds like a pretty good idea, rip the monkeys they will all be harvested for their leather
> Any chance of pickaxes and shovel heads being equipped onto any mini or medium tool-stick for their respective portable subtypes?
i didn't make the sprites with this in mind but i could edit them since it seems like a pretty good idea

**Comment by thichbriars** [comment]
Hey can you send me the sprites for like a handle and a tool head, and the full tool once its complete?

**Comment by TrickyDickRichard** [comment]
all that i've sprited for this so far excluding the throwing knife is in the picture in the op, just download it and replace the ".png" with ".dmi"

**Comment by thichbriars** [comment]
wondering if you had an idea for the crafting recipes for each item. like which rod goes to each. also not  sure if i need a separate sprite for the finished product.

**Comment by TrickyDickRichard** [comment]
i was thinking it would just be put the tool head on the tool rod and bob's your uncle and that certain forged items would accommodate either one or multiple sizes of tool rod, like the tool heads would be able to be full size or mini, but something like the greatsword and the warhammer would absolutely require a large rod. and i think you could just make these by having the actual item be determined by the forged item's sprite and then overlaying that on a tool rod sprite

**Comment by thichbriars** [comment]
yeah also can you do the spirtes for the rest of the weapons already in the game? dont wanna remove stuff

**Comment by TrickyDickRichard** [comment]
ok i made the small rod exist and i edited the sprites so you could mix and match rods and heads, also dagger and shovel exist now. editing op

**Comment by thichbriars** [comment]
sick i think i found a way to overlay the sprites. just tryna code this in a way that dosent piss anyone off.

**Comment by TrickyDickRichard** [comment]
apologies, but you no longer have permissions to use my sprites

**Comment by AnthonyJNgo** [comment]
@TrickyDickRichard You already sent them to us, thanks.

**Comment by steamp0rt** [comment]
@TrickyDickRichard if you committed them to an (A)GPL codebase, your permission is not needed.

**Comment by TrickyDickRichard** [comment]
ok dont care now bye bye

**Comment by AnthonyJNgo** [comment]
@TrickyDickRichard #12574
