### ISSUE TITLE
[Sugg] Frag grenade casings

### ISSUE THREAD

**Issue by TrickyDickRichard** [HippieStation/HippieStation#12281]
[Title]: Frag grenade casings

[Implementation]: Here's the idea:
Isn't it weird how grenade casings that utilize explosives in them do not throw any shrapnel? I guess it could make sense, but what if I want to make a shrapnel grenade? Why not just add some screwdrivers to the grenade casing? Maybe 10 or 15 screwdrivers and some duct tape on a grenade casing would make a frag grenade casing. It would still need to be assembled like a normal grenade casing, but when it detonates, multiple screwdrivers fly in every direction, potentially bouncing off walls and embedding in unarmored targets. But, without any explosive force to throw the screwdrivers, they would just fall off the casing as it disappears, doing no harm to anybody. This means that a potassium+water frag grenade would shoot screwdrivers in every direction, but a smoke mixture or fire mixture in a frag grenade casing would simply result in the screwdrivers laying on the ground, doing nothing.

[Why]: It adds more explosives variety, more improv. weapon variety, a use for low yield explosive mixtures in grenades, as the screwdrivers wouldn't need that much explosive force(such as from BP or Nitroglycerin) to be dangerous in a close enough range. Also, embedding screwdrivers in people is always fun.

[Resources]: Sprite wouldn't be too hard to make, it's just a grenade casing with screwdrivers taped to it. Would need someone to code it, though.

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by karmaisblackandbluepilled** [comment]
+1 but for shit like glass shards too

**Comment by TrickyDickRichard** [comment]
i don't think glass shards would work for this, maybe metal rods and kitchen knives could work as well

**Comment by mkikt4743** [comment]
less screwdrivers or just use like 5 shards/rods, if done then +1

**Comment by TrickyDickRichard** [comment]
well, "one in every direction" in BYOND means literally 8 and I imagine full rods would be too big for a grenade so they'd get chopped in half and that would be 4

**Comment by hovershift01** [comment]
in forge you could probably make fragments or similar and add to the grenade
this would allow the frag grenades have any material as fragments

**Comment by illusineer** [comment]
dope
