### ISSUE TITLE
[Sugg] Megaphone Blasters

### ISSUE THREAD

**Issue by TrickyDickRichard** [HippieStation/HippieStation#12510]
[Title]: MEGAPHONE BLASTERS

[Implementation]: You know how in old Lego Star Wars kits all the guns were just megaphones backwards with transparent studs on the ends? We have megaphones. A craftable item, the blaster, can be made with a megaphone(like from the closets of the Heads), a piece of expensive glass(I don't really know what this would be, maybe plasma glass or plastanium glass?), and some duct tape and you've made a blaster! I don't know how much damage it should to to make it even remotely balanced, but the Lego Blaster in Lego Star Wars does one heart of damage, and the player has four.

[Why]: MORE MAKESHIFT SHIT, also because it's a good reference to something we have very little references to.

[Resources]: I can sprite the blaster itself, and this could go either in the style of "it's really just a command megaphone with a circle on it" or in the style of "it's a Lego megaphone with a stud on it". Code would have to be done by someone else.

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by ElephantSeal** [comment]
yes

**Comment by thebiggestboss** [comment]
funny idea and is gonna be ez enough with sprites. i'll start working on the code using your sprites, i'll talk with designers about balance and whatnot
