### ISSUE TITLE
Strip all TGUI interfaces down to HTML

### ISSUE THREAD

**Issue by KingTerrytheTerrible** [HippieStation/HippieStation#12545]
Fuck tgui man, what a slow bloated piece of shit. Doesn't even look that good and has no white theme so the contrast is all fucky

**Comment by karmaisblackandbluepilled** [comment]
+1 GOD WILLS IT

**Comment by steamp0rt** [comment]
-1

tgui-next was made to be fast. If it is slow, it is not the fault of it. I have never had any problems on the main server with it. I have not HEARD of any problems with it. You are simply attempting to remove this over personal opinion, and I do not like this at all.

**Comment by KingTerrytheTerrible** [comment]
> 
> 
> -1
> 
> tgui-next was made to be fast. If it is slow, it is not the fault of it. I have never had any problems on the main server with it. I have not HEARD of any problems with it. You are simply attempting to remove this over personal opinion, and I do not like this at all.

Marked as spam

**Comment by KingTerrytheTerrible** [comment]
hurr durr lets send a 10mb javascript file so you can hack a door

**Comment by karmaisblackandbluepilled** [comment]
>>everyone complains about the fact that pages load up as white
>>hurr i never heard of problems with it

God is with Karma.

**Comment by steamp0rt** [comment]
The main RSC is easily 100 MB.

tgui.bundle.js is 427 KB.
tgui.bundle.css is 51.5 KB.

Also, are the white screens ever actually tgui? The "Join Game / Ready" box is not tgui.

**Comment by KingTerrytheTerrible** [comment]
>500KB
you know how long byond takes to transfer that right

**Comment by karmaisblackandbluepilled** [comment]
yeah and join game / ready were never whited for me, unlike shit like the hacking interface or chemistry ui

**Comment by steamp0rt** [comment]
@KingTerrytheTerrible if 500 KB is a problem, I hope no admin ever does a global sound or uploads a custom lobby screen!

**Comment by steamp0rt** [comment]
@karmaisblackandbluepilled I've never had issues with any of those. Could you link an actual issue report relating to the issue?

**Comment by KingTerrytheTerrible** [comment]
NOBODY MAKES ISSUES

**Comment by KingTerrytheTerrible** [comment]
HURR DURR LET ME RECOMPILE TGUI EVERY TIME I WANT TO UPDATE A UI

**Comment by steamp0rt** [comment]
HURR DURR LET ME RECOMPILE THE ENTIRE DMB EVERY TIME I WANT TO UPDATE A UI

**Comment by KingTerrytheTerrible** [comment]
HURR DURR LETS HAVE A WHOLE FUCKING SUBSYSTEM FOR A MICROWAVE

**Comment by karmaisblackandbluepilled** [comment]
i have literally never made an issue report and I will never make one.

**Comment by steamp0rt** [comment]
@karmaisblackandbluepilled well then idc about your bugs then

**Comment by KingTerrytheTerrible** [comment]
what a great maintainer ideology

**Comment by steamp0rt** [comment]
1. I can't DO anything with just "it no work"
2. I'm not going to actively search chat for "it no work"

**Comment by KingTerrytheTerrible** [comment]
Don't  worry guys, I'll fix all your slow UI issues that dont work!

**Comment by karmaisblackandbluepilled** [comment]
smdh steamport isn't even nazbol
for real though, tgui gay, give us html, give us old chat, give us glory

**Comment by zamolxius** [comment]
honestly a bit of selectivity would be cool,  tgui next and html are both good for different purposes 

chemistry dispenser and nuke interfaces are great in tgui next because the first you keep open and its smooth and the second looks way better than before.  for other shit like airlock hacking which should initialize quickly and let you crack em open without the gay tgui loading,  html is better

**Comment by KingTerrytheTerrible** [comment]
nuke interface is really confusing with the new gui imo. chem dispenser can use TONS of polish but the thing is it doesnt need to be TGUI which just limits you to a certain style

**Comment by Toxici11i** [comment]
> -1
> 
> tgui-next was made to be fast. If it is slow, it is not the fault of it. I have never had any problems on the main server with it. I have not HEARD of any problems with it. You are simply attempting to remove this over personal opinion, and I do not like this at all.

TGUI Next is hell, converting anything to TGUI next takes time effort and most importantly the ability to understand ReactJS's syntax.

fuck TGUInext

**Comment by Toxici11i** [comment]
> @KingTerrytheTerrible if 500 KB is a problem, I hope no admin ever does a global sound or uploads a custom lobby screen!

Remember when custom sounds could cause the server to hang trying to send it to all clients at once?

yeah me too

**Comment by Toxici11i** [comment]
@steamp0rt the point is, newer TGUI interfaces may look nicer, but make me want to fucking die in terms of syntax. They also are ((large))

**Comment by steamp0rt** [comment]
@Toxici11i you are literally the only person on Hippie (except maybe diego) who I believe has an utterly worthless opinion.

**Comment by FantasticFwoosh** [comment]
+1

Why not just make simplified _HipGui_ instead to be simplified and run smoother with a better browser.

**Comment by steamp0rt** [comment]
@FantasticFwoosh I'd LOVE to see your plans for such a thing.

**Comment by AnthonyJNgo** [comment]
We need a list of pros and cons, and screenshots.

**Comment by yoyobatty** [comment]
This isn't gonna happen since tgui next is op and if you so decide to code it, please allow us to have both options.
