### ISSUE TITLE
[Sugg] Modular Firearms

### ISSUE THREAD

**Issue by TrickyDickRichard** [HippieStation/HippieStation#12563]
[Title]: MODULAR FIREARMS

[Implementation]: You ever see the weapon customization in Escape From Tarkov? In a nutshell, take a receiver of a certain mechanism and caliber, attach a barrel of a certain length, and attach a stock of a certain type, and you have a firearm. Modular receivers, the ones used to make pipe shotguns, can be stabbed with a screwdriver to change the mechanism, from the default Break-Barrel, Bolt-Action, Semi-Automatic IM(internal magazine), Semi-Automatic DM(detachable magazine), and Full-Auto. Also changed would be chambering, basically any cartridge could be allowed or disallowed for balance reasons. Also for balance reasons, forge bullets made of anything but iron would be disallowed and instantly blow up in your face if discharged. A barrel of 4.5 in, 9 in, 16 in, and 22 in, made with a pipe and a welder, would change size and effectiveness, and semi- or full-auto guns would require a gas system to be installed. Finally, a stock and fore made of wood or plastic would be installed, effecting size and accuracy. Clips and magazines would be able to be made for the guns using metal and simple tools, though the former would be much easier to make. Magazines would also have different sizes, such as Hunting(3-5 rnds), Compact(9-15), Standard(18-30), and Drum(54-90), the latter requiring bluespace crystals to make, and all with capacities dependent on caliber.

[Why]: More options are good options, modular stuff is better, and makeshift shit is the best.

[Resources]: For sprites, epic gamer#0295 and I (mr pibb#6156) are willing to sprite, someone else would have to code it.

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by MrEpicSax** [comment]
Blessed

**Comment by mkikt4743** [comment]
I can do sprites gimme a week
