### ISSUE TITLE
Invisible alt-skins for the double-barrel shotgun

### ISSUE THREAD

**Issue by TrickyDickRichard** [HippieStation/HippieStation#3103]
Round ID: 22392

I attempted to use alt-click to reskin my shotgun, after I did the shotgun had no sprite. I chose Maple, but the other skins might be broken as well. I need my gun Fashion Souls.

**Comment by PopNotes** [comment]
actually this is fashionrim

**Comment by banthebantz** [comment]
old issue

**Comment by JamieH** [comment]
Confirmed fixed.
