### ISSUE TITLE
dismembered limbs still show up when viewed from the side

### ISSUE THREAD

**Issue by Spacedong** [HippieStation/HippieStation#3840]
this bug has been present for 2 years

https://vgy.me/vNDGSE.png

**Comment by Pyko1** [comment]
Intended hippiefeature to piss off you, not gonna get fixed unless TG fixes it.

**Comment by Pyko1** [comment]
aka upstream issue

**Comment by tortellinitony** [comment]
if you want to resprite all clothing items so this doesn't happen,  be my guest
