### ISSUE TITLE
people in the process of cloning have no hearts

### ISSUE THREAD

**Issue by Spacedong** [HippieStation/HippieStation#4272]
what the fuck

**Comment by banthebantz** [comment]
so what they die while cloning?

**Comment by DinduStuffin** [comment]
If you use the heal command on them as an admin while they're cloning, they instantly die, yes, but if they're fully cloned they live iirc.

**Comment by banthebantz** [comment]
I'm edging towards this being intended, albeit weird behavior.

Regardless this is certainly upstream as far as I know so you're better off making the issue report there.

**Comment by GuyonBroadway** [comment]
Was the cloning pod emagged?

**Comment by tortellinitony** [comment]
Your organs and limbs take time to appear while you clone. If they don't die while cloning, then this is probably intentional

**Comment by Spankmaster1066** [comment]
If what Tony said is true doesn't seem like a bug.

**Comment by banthebantz** [comment]
I agree, closing.
