### ISSUE TITLE
Copypasting from the chat doesn't work

### ISSUE THREAD

**Issue by Spacedong** [HippieStation/HippieStation#4273]
title, copying and pasting shit does not work at all

**Comment by banthebantz** [comment]
Works fine for me

**Comment by GuyonBroadway** [comment]
When was the last time you updated windows/internet explorer/ directX

**Comment by Spankmaster1066** [comment]
I got this when trying to paste stuff from browser INTO byond, but not vice versa. I believe it's because of weird hidden unicode chars.

**Comment by Spankmaster1066** [comment]
Dong now reporting this was fixed by relogging.
