### ISSUE TITLE
Several game breaking clockwork cult bugs

### ISSUE THREAD

**Issue by Blute1** [HippieStation/HippieStation#4352]
The spam filter applies to repeated clockwork cult chants, muting you in all forms of IC if you say them too much. Only 1 of the 5 computers in Reebe actually works and is oriented at the station. The rest are oriented to thunderdome and don't work.

**Comment by McBawbaggings** [comment]
this happens with holoparasite cries too and such
it's to do with calling saycode too quickly

**Comment by GuyonBroadway** [comment]
You can use the "jump to camera" UI button to get from thunderdome to station.

**Comment by Spacedong** [comment]
it shouldnt start on the thunderdome though
