### ISSUE TITLE
THE WORST FUCKING BUG IVE EVER FUCKING SEEN [URGENT] [FUCK] [HOLY SHIT]

### ISSUE THREAD

**Issue by Spacedong** [HippieStation/HippieStation#4353]
YOU CAN SPAWN YOUR FUCKING BLOB OVERMIND AS A GHOST IN REEBE AND INSTANTLY DESTROY THE ARK, HOLY FUCK IM LITERALLY HAVING AN ANEURYSM, AN HOUR AND A HALF WASTED JUST BECAUES SOME FUCK CAN SPAWN HISF UCKING BLOB IN THE FUCKING ARK ON REEB WITHOUT ANYTIHNG HAPPENING FUCK FUCK FUCK

**Comment by GuyonBroadway** [comment]
upstream issue report it here pls! 

https://github.com/tgstation/tgstation/issues

**Comment by MoreRobustThanYou** [comment]
https://github.com/tgstation/tgstation/pull/32173
