### ISSUE TITLE
Urgent Issue: The gulag has no point console, just a regular stacking console.

### ISSUE THREAD

**Issue by Spacedong** [HippieStation/HippieStation#4414]
The gulag needs a /obj/machinery/mineral/labor_claim_console. Right now it only has a /obj/machinery/mineral/processing_unit_console. 

![](https://vgy.me/TsNt0u.png)

**Comment by GuyonBroadway** [comment]
The points claim module is on the shuttle by the shuttle sheet stacker NERD!!
