### ISSUE TITLE
the internals system prioritizes plasma tanks over oxygen tanks

### ISSUE THREAD

**Issue by Blute1** [HippieStation/HippieStation#4511]
![image](https://user-images.githubusercontent.com/12958054/32287138-34921fde-bf06-11e7-8a50-65607ab3c0b3.png)
![image](https://user-images.githubusercontent.com/12958054/32287146-3a9ac26e-bf06-11e7-90e3-7b7695216961.png)

**Comment by GuyonBroadway** [comment]
Did you try swapping the tanks over just in case it was prioritising tanks in hand over tanks in pockets?

**Comment by McBawbaggings** [comment]
it's slot dependent not type dependent
https://github.com/HippieStation/HippieStation/blob/9752ae9ad1e61ed140e05bf829fc64f89344e29b/code/_onclick/hud/screen_objects.dm#L266
it checks your hands first which is why this happened

**Comment by JohnGinnane** [comment]
![image](https://user-images.githubusercontent.com/3355198/32681892-a867755c-c669-11e7-9565-8f440152fa75.png)
