### ISSUE TITLE
Trying to hit downed people or clicking them doesn't work sometimes

### ISSUE THREAD

**Issue by Blute1** [HippieStation/HippieStation#4572]
Issue is sporadic and doesn't happen often, but when it does its the most frustrating thing, multiple players can attest to it happening, but good luck fixing it since your shitty policies mean any /tg/ mirrors are pretty much instantly merged without actually seeing if they're good or not :/

**Comment by GuyonBroadway** [comment]
We can undo tg balance internally, we merge them not with the intent of using their balance but so we can steal their bugfixes and good features conflict free.

**Comment by Spacedong** [comment]
well obviously your conflict free system got fucked up nigga

**Comment by McBawbaggings** [comment]
if we don't merge /tg/ mirrors then honkbot shits itself and can't merge properly
the best option is merge and override what we don't like

**Comment by GuyonBroadway** [comment]
Think of it as rebasing to latest tg and undoing their shit but instead of having to do months of work and being super out of date by the time we are done, we only have to do a little bit of work each week and are seldom out of date.

**Comment by Spacedong** [comment]
except we infect ourselves with their shitty features, bug fixes are good but shitty features arent

**Comment by GuyonBroadway** [comment]
You missed the point we can and do undo their shitty features and no the way you hate the rad system because it makes the position of the rad collectors a little different does not count.

**Comment by Spacedong** [comment]
im over the rad shit

**Comment by JohnMcLaime** [comment]
Also what the fuck is wrong with hitboxes in general? Especially when person is down, it still can be hit if you click above it, where it would have a sprite if it was standing.

**Comment by Carbonhell** [comment]
Finally fixed seems, wew lad
