### ISSUE TITLE
dismembered limbs still show up from the side

### ISSUE THREAD

**Issue by Blute1** [HippieStation/HippieStation#4740]
https://vgy.me/vNDGSE.png

still happens 2 years on, if you close this issue you are refusing to acknowledge its existence

**Comment by PopNotes** [comment]
The limb isn't there, you're seeing the side of the torso. It's an issue, but one that's nearly impossible to fix unless someone wants to completely rework sprite layering and fix every single clothing item in the game

**Comment by Blute1** [comment]
it still deserves to stay as open for eternity until some brave lad attempts to fix it

**Comment by PopNotes** [comment]
This is something that needs to be brought up upstream, not here. Hippie contributors are autistic, but not autistic enough about this kind of shit to ever realistically achieve it. Bitch to /tg/, maybe some of their drooling drones will do something about it.

**Comment by optimumtact** [comment]
hippie admits they just dont' have the hot sauce to make noodle soup

**Comment by PopNotes** [comment]
we have bigger problems, like flux being alive
