### ISSUE TITLE
the nuke ops escaping on the emergency shuttle does not count for major syndicate victory

### ISSUE THREAD

**Issue by Blute1** [HippieStation/HippieStation#4758]
Instead, it says that the ops died in the process, giving the Total Annihilation ending

**Comment by GuyonBroadway** [comment]
If they escaped via emergency shuttle centcomm will have deathsquids waiting.

**Comment by GuyonBroadway** [comment]
Otherwise sounds like an upstream

**Comment by JohnMcLaime** [comment]
They dont need to escape, jetpacking to other zlvl will work since at least 1 nukie has to be alive.

**Comment by Carbonhell** [comment]
Fixed long ago seems.
