### ISSUE TITLE
the emergency shuttle can get stuck in transit, infinitely.

### ISSUE THREAD

**Issue by Blute1** [HippieStation/HippieStation#4884]
![](https://vgy.me/vy0aDn.png)

**Comment by Blute1** [comment]
Round ID #24468

**Comment by praisenarsie** [comment]
looks a lot like the arrivals shuttle to me mister

**Comment by JohnGinnane** [comment]
@Blute1 has this happened since you reported it?

**Comment by Carbonhell** [comment]
Cannot reproduce/never happened anymore, closing
