### ISSUE TITLE
the ERT team can legit just go through the centcom airlocks to the centcom dock and board the emergency shuttle or take shit from the freedom vendor

### ISSUE THREAD

**Issue by Blute1** [HippieStation/HippieStation#4901]
this is all you need to know to see that TG is a joke

**Comment by praisenarsie** [comment]
not a bug, feature

admins can just smite anyway

**Comment by Spankmaster1066** [comment]
What kind of retarded feature is that? Why is it necessary to be a feature? Because ERT should regularly have access to vending machines with a ton of dangerous and powerful guns? 

It's only in edge cases that you'd WANT them to access it.

**Comment by Chnkr** [comment]
The freedom vendor is a hippie feature, not a TG feature

**Comment by banthebantz** [comment]
simple: blacklist freedom vendor from those with mindshield implants (aka the non free)

**Comment by McBawbaggings** [comment]
punish ERT if they don't ERT properly
golly gee

**Comment by praisenarsie** [comment]
or just map it in so there are shutters that open at the freedom vendor when shuttle docks

**Comment by Pyko1** [comment]
no freedom vendor or armory anymore
