### ISSUE TITLE
CTRL+clicking on things no longer stops pulling them

### ISSUE THREAD

**Issue by Blute1** [HippieStation/HippieStation#5241]
[Directions]: # (INCLUDE THE ROUND ID from the Status panel or retrieve it from https://atlantaned.space/newSS13tools/round.php ! If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead. Explain your issue in detail, including the steps to reproduce it.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by JohnGinnane** [comment]
I thought it only started pulling them?

**Comment by praisenarsie** [comment]
i suspect @ninjanomnom is at fault here

🕵️

**Comment by banthebantz** [comment]
remove math

**Comment by GuyonBroadway** [comment]
ctrl+click initates a grab action, this is intended
