### ISSUE TITLE
you can grab people from inside a locked locker, then pull them into the locked locker with you and they can't get out

### ISSUE THREAD

**Issue by Spacedong** [HippieStation/HippieStation#527]
bullshit retarded bug how could you let this happen

also it was pretty fucking funny a guy slipped like 5  dudes and then dragged them into the locker he was in

**Comment by QuarianCommando** [comment]
Wonder how hard it would be to fix this for every locker except the clown locker

**Comment by Carbonhell** [comment]
tunnel clown: locker edition

**Comment by McBawbaggings** [comment]
Tried replicating it, can't do it.
Is there some prerequisite for it?

**Comment by Carbonhell** [comment]
can confirm it does not happen normally
closing until someone does a better issue report
