### ISSUE TITLE
the eminence is straight up broken

### ISSUE THREAD

**Issue by Blute1** [HippieStation/HippieStation#5394]
Boring ass role that does nothing but mark directions. It's like a shitty AI that can't do anything but can only call out stuff. Clock cult is overpowered as it is. It's also fucking spelled wrong. 

![](https://vgy.me/5xtBBl.png)

Furthermore, you can't open up the player panel of a person playing the eminence, nor does one's ahelps show.

**Comment by GuyonBroadway** [comment]
not an issue
