### ISSUE TITLE
space vines can spread in space

### ISSUE THREAD

**Issue by Blute1** [HippieStation/HippieStation#5414]
![](https://vgy.me/180Kfv.png)

this bug was fixed a long time ago, guess our constant TG rebases got rid of the fix

**Comment by MoreRobustThanYou** [comment]
It's a vine mutation I believe

**Comment by Chnkr** [comment]
Pretty sure it's a feature

**Comment by GuyonBroadway** [comment]
1, thats a mutation they can get 2: they are fucking "SPACE VINES" of course they can be in space.
