### ISSUE TITLE
make ash walker eggs only possessable 30 mins in (notice for erik)

### ISSUE THREAD

**Issue by Blute1** [HippieStation/HippieStation#5433]
aga

**Comment by xTrainx** [comment]
nice meme

**Comment by JohnMcLaime** [comment]
This makes far ashligger spawn even worse, making it even less likely for them to get onto station.
Close spawns will be killed off by miners, this will just make ashliggers non existent, they are already gimped and can only use melee, also they get cucked by glass.

**Comment by GuyonBroadway** [comment]
Make a suggestion on the forums pls.
