### ISSUE TITLE
mousing over an object doesn't show its name anymore

### ISSUE THREAD

**Issue by Blute1** [HippieStation/HippieStation#7107]
![](https://vgy.me/7hTEuS.png)

**Comment by Kawaii-Big-Boss** [comment]
Is your mouse glitching the fuck out or something? This happens sometimes. I blame /tg/

**Comment by GuyonBroadway** [comment]
byond version?

**Comment by Blute1** [comment]
latest byond version on beta

**Comment by Carbonhell** [comment]
it does tho, cannot reproduce
