### ISSUE TITLE
screaming and farting still bugged

### ISSUE THREAD

**Issue by Blute1** [HippieStation/HippieStation#7108]
you have to do shift letter instead of ctrl + letter, and if you do shift S your guy moves down

**Comment by Kawaii-Big-Boss** [comment]
Not a bug.

**Comment by Chnkr** [comment]
Bug

**Comment by GuyonBroadway** [comment]
I had to sue shift+s as ctrl+s has tg related functionality and I'm not sure how to stop soemone from movng when using the new hotkeys system, the only alternative would be to bind it to something else.

**Comment by Blute1** [comment]
well its still bugged, remove the new hotkeys system as nobody uses it

**Comment by tortellinitony** [comment]
Yes going to disable moving when holding shift soon. I think we should stick with shift for emote hotkeys though.

**Comment by JohnGinnane** [comment]
Not a bug, an unfortunate but necessary "feature" so we can still have shortcuts for those functions
