### ISSUE TITLE
Slimes and beepsky

### ISSUE THREAD

**Issue by Pyko1** [HippieStation/HippieStation#7595]
I don think this is entirely intended.
![slime beeps](https://user-images.githubusercontent.com/12048747/40002254-ccf1be30-5798-11e8-9d2c-e7b93f55cb16.PNG)

**Comment by AnthonyJNgo** [comment]
This should be very easy fix. Will check out tonight.

**Comment by Jujumatic** [comment]
$1 easy fix

**Comment by AnthonyJNgo** [comment]
Approved for $2, Beepsky should be immune to these slimes.

**Comment by HideAndSeekLOGIC** [comment]
@k-k-karma reference these next time

please

Also, check if the bounties came through.

**Comment by AnthonyJNgo** [comment]
@k-k-karma You need to send me the links to your fixes so I can merge them and make sure you get paid.
