### ISSUE TITLE
Endless carbonhells cheap cuisine

### ISSUE THREAD

**Issue by Pyko1** [HippieStation/HippieStation#7597]
If you spamclick the the can before selecting food type, it will just keep on opening the menu and making more food once you select the food type.

**Comment by Jujumatic** [comment]
OOH so this explains that one time where i managed to get two butterdogs for some reason

**Comment by Carbonhell** [comment]
>not sanityzing input 
Lmfoa

**Comment by yoyobatty** [comment]
I'm working on fixing this

**Comment by zamolxius** [comment]
fixed

**Comment by JohnGinnane** [comment]
thanks homie
