### ISSUE TITLE
clone pods make beeping constant noises

### ISSUE THREAD

**Issue by Blute1** [HippieStation/HippieStation#8219]
title, annoying as fuck

**Comment by yoyobatty** [comment]
Have you tried dragging the body inside it out. Autoprocess will continue to attempt to scan a body regardless if it's alive or dead. I could probably have a check to see if they are cloneable so it doesn't spam.

**Comment by Blute1** [comment]
well I mean it keeps checking to see if the body is cloneable even when the dude's new body was in the clone pod, so that's probably a bug and why it kept beeping
