### ISSUE TITLE
[Suggestion] Butt-to-Moth CPR

### ISSUE THREAD

**Issue by Pyko1** [HippieStation/HippieStation#9274]
[Implementation]: Remove normal CPR from moths, and instead you use Butt-to-Moth CPR.
To Perform Butt-to-Moth CPR you get in top of the critted moth and perform a fart with help intent.
Unlike CPR, this action is not restricted by mask, but an exosuit instead on the helper. The  Butt-to-Moth CPR has normal timer but has 0% of farting your butt of to avoid ahelp spam.

_Bix Nood is attempting to perfrom Butt-to-Moth CPR on Mothshit._
_Bix Nood farts on Mothshit pumping methane in his lungs!_

_You feel fresh fart entering your lungs!_

[Why]: Everyone knows that moths are shit eating, methane breathing pests, and it is a natural instinct for anyone who sees a critted moth to fart on them, so this is actually a buff to moths.

**Comment by biggiOS** [comment]
wh

**Comment by bubberducky2** [comment]
:thinking:

**Comment by GuyonBroadway** [comment]
Proof that even god avoids Finland.

**Comment by Dinopeaks** [comment]
+1, this or remove moths

**Comment by Pyko1** [comment]
What you mean, this divine insight is clearly from god!

**Comment by GuyonBroadway** [comment]
Finnish God is a violent drunkard who stands in the town fountain with his trousers down and picks fights with the local pigeons.

**Comment by Pyko1** [comment]
you forgot the russians, swedes and the refugees.

**Comment by fluxcapacitor1337** [comment]
+1

**Comment by Eagle-Eyess** [comment]
+1

**Comment by ExpAntique** [comment]
+1

**Comment by Eagle-Eyess** [comment]
+1

**Comment by AnthonyJNgo** [comment]
Stale. Make a new suggestion post if you legitimately want this in.

**Comment by Pyko1** [comment]
only reason its stale is because you headmins never voted on it!
