### ISSUE TITLE
Suggestion: Carbonhell's Can of Cheap Cuisine is edible for Carbonhell

### ISSUE THREAD

**Issue by biggiOS** [HippieStation/HippieStation#9350]
[Implementation]: People with the ckey or name "Carbonhell" can eat food like butterdogs and potato pizzas without getting disgusted

[Why]: Makes sense for a chef to like his own food

[Resources]: Simple coding 

@HippieStation/maintainers

**Comment by zamolxius** [comment]
not really useful in any way but an afterthought,  id say.  kinda snowflake code
also those foods often contain harmful chemicals so it'd be useless anyways

**Comment by Kawaii-Big-Boss** [comment]
@Carbonhell Of course _you_ would
![sam](https://user-images.githubusercontent.com/33744849/46376699-a3af3d00-c664-11e8-90d0-9b33e93944a4.jpg)
 say that

**Comment by bubberducky2** [comment]
+1 make him also be able to eat inedible items aswell, AKA shit :smirk:

**Comment by Eagle-Eyess** [comment]
id say +1 but if it is that hard to code and and problematic than no -1

**Comment by praisenarsie** [comment]
it isn't hard to code but there's no point in adding it
