### ISSUE TITLE
[Suggestion] Allow more broad selection of mutant colors and hairs

### ISSUE THREAD

**Issue by Pyko1** [HippieStation/HippieStation#9391]
[Implementation]: # Allow Mutant races pick darker character colors, as well as possibly hair styles.

[Why]: # I got this urge to play darker than allowed lizard/IPC with an afro.

[Resources]: # All resources are already in the game

**Comment by biggiOS** [comment]
more reasons for people to play liggers -1

**Comment by MrWankman** [comment]
I would advocate for IPC's to have more selections for their screens than the 5 or so animated ones at least. Like having a static color selection so you can meme with it's aesthetic more. Robots are better than lizzards anyways.

**Comment by zamolxius** [comment]
hey,  if humans can be 255 colored,  why can't ligs and boxes

**Comment by AnthonyJNgo** [comment]
Stale.
