### ISSUE TITLE
vore is overpowered

### ISSUE THREAD

**Issue by k-k-karma** [HippieStation/HippieStation#9603]
permadeath, there's no way to get the person you vored out of your body while permadeath should be hard and challenging

**Comment by zamolxius** [comment]
vore?  by alien? you can regurgitate iirc

**Comment by k-k-karma** [comment]
no human vore

**Comment by zamolxius** [comment]
human eating monkey you mean?

**Comment by k-k-karma** [comment]
yes

**Comment by zamolxius** [comment]
it only works when fat though?  and its a nice little feature.  let it be,  its a remnant of the old times

**Comment by k-k-karma** [comment]
so what if you're fat you can go the same speed w/ a secway. vore is unbalanced and you cant change my mind

**Comment by zamolxius** [comment]
monkeys are valid anyways
make eating two monkeys gib yoh

**Comment by AnthonyJNgo** [comment]
This was denied twice already.
