### ISSUE TITLE
TTS is gone

### ISSUE THREAD

**Issue by yobob591** [HippieStation/HippieStation#9768]
Title, TTS is completely inoperable.

TTS was easily the best feature hippie had and brought us a HUGE population boost, and after tons of effort to finally get it to work it worked for a week then broke. Fun features like TTS are really the heart and soul of hippie, so I think this really needs to be a higher priority fix here.

**Comment by zamolxius** [comment]
THIS.  we have people on reddit asking about TTS so theres some public attention we can capitalize on

**Comment by Dinopeaks** [comment]
from what i hear since the box is on Linux and TTS is windows application it is dead untill we port it

**Comment by k-k-karma** [comment]
TTS was major fucking shitcode

**Comment by Tranquill6** [comment]
SS13 code is just a big firey garbage heap, but TTS was that with a big pile of smelly shit on it.

**Comment by k-k-karma** [comment]
ill end up redoing it later

**Comment by Carbonhell** [comment]
#10482
