### ISSUE TITLE
[Sugg] Add Half Life Scientist scream as Alt scream for research

### ISSUE THREAD

**Issue by yobob591** [HippieStation/HippieStation#9804]
Title
[Implementation]: If someone is a scientist/roboticist/RD make some of the scientist screams from Half Life 1 alternate screams. Either it could check what ID they have or if possible check what job they had at round start.
[Why]: STAHP
[Resources]: https://www.youtube.com/watch?v=jfrL4GFsyDY

**Comment by WarRage333** [comment]
https://youtu.be/FygQ0aMS1Oo?list=PLE_RVFxwfFCpqdsdQGS8oGtPRdzCZOQpJ


+1

**Comment by HideAndSeekLOGIC** [comment]
definitely +1

**Comment by Kawaii-Big-Boss** [comment]
Yes

**Comment by zamolxius** [comment]
or base it on the labcoat
